// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all actors GET /actors */
export async function actorControllerFindAll(
  // Param type generated by superposition
  params: API.ActorControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<any>("/actors", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create a new actor POST /actors */
export async function actorControllerCreate(
  body: API.CreateActorDto,
  options?: { [key: string]: any }
) {
  return request<any>("/actors", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get an actor by ID with all contents GET /actors/${param0} */
export async function actorControllerFindOne(
  // Param type generated by superposition
  params: API.ActorControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/actors/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update an actor PUT /actors/${param0} */
export async function actorControllerUpdate(
  // Param type generated by superposition
  params: API.ActorControllerUpdateParams,
  body: API.UpdateActorDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/actors/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete an actor DELETE /actors/${param0} */
export async function actorControllerRemove(
  // Param type generated by superposition
  params: API.ActorControllerRemoveParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/actors/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get top actors by number of contents GET /actors/top/list */
export async function actorControllerGetTopActors(
  // Param type generated by superposition
  params: API.ActorControllerGetTopActorsParams,
  options?: { [key: string]: any }
) {
  return request<any>("/actors/top/list", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}
