// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all actors GET /api/v1/actors */
export async function actorsControllerGetActors(
  // Param type generated by superposition
  params: API.ActorsControllerGetActorsParams,
  options?: { [key: string]: any },
) {
  return request<any>("/api/v1/actors", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create actor POST /api/v1/actors */
export async function actorsControllerCreateActor(
  body: API.CreateActorDto,
  options?: { [key: string]: any },
) {
  return request<any>("/api/v1/actors", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get an actor by ID with all contents GET /api/v1/actors/${param0} */
export async function actorsControllerGetActorById(
  // Param type generated by superposition
  params: API.ActorsControllerGetActorByIdParams,
  options?: { [key: string]: any },
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/actors/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Delete actor DELETE /api/v1/actors/${param0} */
export async function actorsControllerDeleteActor(
  // Param type generated by superposition
  params: API.ActorsControllerDeleteActorParams,
  options?: { [key: string]: any },
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/actors/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update actor PATCH /api/v1/actors/${param0} */
export async function actorsControllerUpdateActor(
  // Param type generated by superposition
  params: API.ActorsControllerUpdateActorParams,
  body: API.UpdateActorDto,
  options?: { [key: string]: any },
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/actors/${param0}`, {
    method: "PATCH",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** Search actors GET /api/v1/actors/search */
export async function actorsControllerSearchActors(
  // Param type generated by superposition
  params: API.ActorsControllerSearchActorsParams,
  options?: { [key: string]: any },
) {
  return request<any>("/api/v1/actors/search", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Get top actors by number of contents GET /api/v1/actors/top */
export async function actorsControllerGetTopActors(
  // Param type generated by superposition
  params: API.ActorsControllerGetTopActorsParams,
  options?: { [key: string]: any },
) {
  return request<any>("/api/v1/actors/top", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}
