// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get paginated category view statistics GET /api/v1/analytics/categories */
export async function analyticsControllerGetCategoriesStats(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetCategoriesStatsParams,
  options?: { [key: string]: any }
) {
  return request<API.ViewStatsItemDtoPaginatedResponseDto>(
    "/api/v1/analytics/categories",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get ML churn and return prediction for users GET /api/v1/analytics/forecast/churn */
export async function analyticsControllerGetChurnPrediction(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetChurnPredictionParams,
  options?: { [key: string]: any }
) {
  return request<API.ChurnPredictionItemDtoPaginatedResponseDto>(
    "/api/v1/analytics/forecast/churn",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Manually trigger churn model retraining POST /api/v1/analytics/forecast/churn/retrain */
export async function analyticsControllerRetrainChurnPrediction(options?: {
  [key: string]: any;
}) {
  return request<any>("/api/v1/analytics/forecast/churn/retrain", {
    method: "POST",
    ...(options || {}),
  });
}

/** Manually trigger forecast model retraining POST /api/v1/analytics/forecast/retrain */
export async function analyticsControllerRetrainForecast(options?: {
  [key: string]: any;
}) {
  return request<any>("/api/v1/analytics/forecast/retrain", {
    method: "POST",
    ...(options || {}),
  });
}

/** Get ML view forecast for contents GET /api/v1/analytics/forecast/views */
export async function analyticsControllerGetViewForecast(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetViewForecastParams,
  options?: { [key: string]: any }
) {
  return request<API.ViewForecastItemDtoPaginatedResponseDto>(
    "/api/v1/analytics/forecast/views",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get paginated movie view statistics GET /api/v1/analytics/movies */
export async function analyticsControllerGetMoviesStats(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetMoviesStatsParams,
  options?: { [key: string]: any }
) {
  return request<API.ViewStatsItemDtoPaginatedResponseDto>(
    "/api/v1/analytics/movies",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get paginated trending movies data GET /api/v1/analytics/trending/movies */
export async function analyticsControllerGetTrendingMovies(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetTrendingMoviesParams,
  options?: { [key: string]: any }
) {
  return request<API.TrendingItemDtoPaginatedResponseDto>(
    "/api/v1/analytics/trending/movies",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get paginated trending TV series data GET /api/v1/analytics/trending/tvseries */
export async function analyticsControllerGetTrendingTvSeries(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetTrendingTVSeriesParams,
  options?: { [key: string]: any }
) {
  return request<API.TrendingItemDtoPaginatedResponseDto>(
    "/api/v1/analytics/trending/tvseries",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get paginated TV series view statistics GET /api/v1/analytics/tvseries */
export async function analyticsControllerGetTvSeriesStats(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetTVSeriesStatsParams,
  options?: { [key: string]: any }
) {
  return request<API.ViewStatsItemDtoPaginatedResponseDto>(
    "/api/v1/analytics/tvseries",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get user statistics and metrics GET /api/v1/analytics/users */
export async function analyticsControllerGetUserStats(options?: {
  [key: string]: any;
}) {
  return request<API.UserStatsDtoResponseDto>("/api/v1/analytics/users", {
    method: "GET",
    ...(options || {}),
  });
}
