// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get paginated category view statistics GET /analytics/categories */
export async function analyticsControllerGetCategoriesStats(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetCategoriesStatsParams,
  options?: { [key: string]: any }
) {
  return request<API.PaginatedViewStatsDto>("/analytics/categories", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Get paginated movie view statistics GET /analytics/movies */
export async function analyticsControllerGetMoviesStats(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetMoviesStatsParams,
  options?: { [key: string]: any }
) {
  return request<API.PaginatedViewStatsDto>("/analytics/movies", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Get paginated trending movies data GET /analytics/trending/movies */
export async function analyticsControllerGetTrendingMovies(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetTrendingMoviesParams,
  options?: { [key: string]: any }
) {
  return request<API.PaginatedTrendingDataDto>("/analytics/trending/movies", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Get paginated trending TV series data GET /analytics/trending/tvseries */
export async function analyticsControllerGetTrendingTvSeries(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetTrendingTVSeriesParams,
  options?: { [key: string]: any }
) {
  return request<API.PaginatedTrendingDataDto>("/analytics/trending/tvseries", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Get paginated TV series view statistics GET /analytics/tvseries */
export async function analyticsControllerGetTvSeriesStats(
  // Param type generated by superposition
  params: API.AnalyticsControllerGetTVSeriesStatsParams,
  options?: { [key: string]: any }
) {
  return request<API.PaginatedViewStatsDto>("/analytics/tvseries", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Get user statistics and metrics GET /analytics/users */
export async function analyticsControllerGetUserStats(options?: {
  [key: string]: any;
}) {
  return request<API.UserStatsDto>("/analytics/users", {
    method: "GET",
    ...(options || {}),
  });
}
