// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** No comments are provided by the backend GET /audit-logs */
export async function auditLogControllerGetLogs(
  // Param type generated by superposition
  params: API.AuditLogControllerGetLogsParams,
  options?: { [key: string]: any }
) {
  return request<API.AuditLogDtoPaginatedResponseDto>("/audit-logs", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** No comments are provided by the backend GET /audit-logs/recent-activity */
export async function auditLogControllerGetRecentActivity(
  // Param type generated by superposition
  params: API.AuditLogControllerGetRecentActivityParams,
  options?: { [key: string]: any }
) {
  return request<API.RecentActivityDtoPaginatedResponseDto>(
    "/audit-logs/recent-activity",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** No comments are provided by the backend POST /audit-logs/video-action */
export async function auditLogControllerCreateLog(
  body: API.AuditLogVideo,
  options?: { [key: string]: any }
) {
  return request<API.AuditLogDtoResponseDto>("/audit-logs/video-action", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}
