// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Send OTP for password reset Sends a 6-digit OTP to the user's email for password reset. OTP expires in 5 minutes. POST /api/v1/auth/forgot-password */
export async function authControllerForgotPassword(
  body: API.ForgotPasswordRequest,
  options?: { [key: string]: any }
) {
  return request<API.OTPResponseResponseDto>("/api/v1/auth/forgot-password", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Resend OTP Resends OTP to user's email. Previous OTPs will be invalidated. POST /api/v1/auth/forgot-password/resend-otp */
export async function authControllerResendOtp(
  // Param type generated by superposition
  params: API.AuthControllerResendOtpParams,
  options?: { [key: string]: any }
) {
  return request<API.OTPResponseResponseDto>(
    "/api/v1/auth/forgot-password/resend-otp",
    {
      method: "POST",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Reset password with OTP Resets user password using verified OTP. The OTP will be marked as used after successful reset. POST /api/v1/auth/forgot-password/reset */
export async function authControllerResetPassword(
  body: API.ResetPasswordRequest,
  options?: { [key: string]: any }
) {
  return request<any>("/api/v1/auth/forgot-password/reset", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** User login POST /api/v1/auth/login */
export async function authControllerLogin(
  body: API.AuthRequest,
  options?: { [key: string]: any }
) {
  return request<API.LoginResponseResponseDto>("/api/v1/auth/login", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Logout and invalidate token DELETE /api/v1/auth/logout */
export async function authControllerLogout(options?: { [key: string]: any }) {
  return request<any>("/api/v1/auth/logout", {
    method: "DELETE",
    ...(options || {}),
  });
}

/** Refresh access token POST /api/v1/auth/refresh */
export async function authControllerRefresh(
  body: API.TokenRequest,
  options?: { [key: string]: any }
) {
  return request<API.TokenResponseResponseDto>("/api/v1/auth/refresh", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Send OTP for registration Sends a 6-digit OTP to user email for account verification during registration. OTP expires in 5 minutes. POST /api/v1/auth/register */
export async function authControllerRegister(
  body: API.RegisterRequest,
  options?: { [key: string]: any }
) {
  return request<API.OTPResponseResponseDto>("/api/v1/auth/register", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Resend OTP for registration Resends a new 6-digit OTP to user email for registration. Previous OTPs will be invalidated. POST /api/v1/auth/register/resend-otp */
export async function authControllerResendRegisterOtp(
  // Param type generated by superposition
  params: API.AuthControllerResendRegisterOtpParams,
  options?: { [key: string]: any }
) {
  return request<API.OTPResponseResponseDto>(
    "/api/v1/auth/register/resend-otp",
    {
      method: "POST",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Verify OTP and complete registration Verifies the 6-digit OTP sent to the user's email and completes the registration process. If verification is successful, the user account is created and activated. POST /api/v1/auth/register/verify */
export async function authControllerRegisterVerify(
  body: API.RegisterWithOtpRequest,
  options?: { [key: string]: any }
) {
  return request<any>("/api/v1/auth/register/verify", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Social login with Google/Facebook Login or register using Google/Facebook OAuth. Automatically creates account if user does not exist. POST /api/v1/auth/social-login */
export async function authControllerSocialLogin(
  body: API.SocialLoginRequest,
  options?: { [key: string]: any }
) {
  return request<API.LoginResponseResponseDto>("/api/v1/auth/social-login", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}
