// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Send OTP for password reset Sends a 6-digit OTP to the user's email for password reset. OTP expires in 5 minutes. POST /auth/forgot-password */
export async function authControllerForgotPassword(
  body: API.ForgotPasswordRequest,
  options?: { [key: string]: any }
) {
  return request<API.OTPResponseResponseDto>("/auth/forgot-password", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** No comments are provided by the backend GET /auth/google/callback */
export async function authControllerGoogleCallback(options?: {
  [key: string]: any;
}) {
  return request<any>("/auth/google/callback", {
    method: "GET",
    ...(options || {}),
  });
}

/** No comments are provided by the backend GET /auth/google/login */
export async function authControllerGoogleLogin(options?: {
  [key: string]: any;
}) {
  return request<any>("/auth/google/login", {
    method: "GET",
    ...(options || {}),
  });
}

/** User login POST /auth/login */
export async function authControllerLogin(
  body: API.AuthRequest,
  options?: { [key: string]: any }
) {
  return request<API.LoginResponseResponseDto>("/auth/login", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Logout user POST /auth/logout */
export async function authControllerLogout(
  body: API.TokenRequest,
  options?: { [key: string]: any }
) {
  return request<any>("/auth/logout", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Refresh access token POST /auth/refresh */
export async function authControllerRefresh(
  body: API.TokenRequest,
  options?: { [key: string]: any }
) {
  return request<API.TokenResponseResponseDto>("/auth/refresh", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Resend OTP for registration Resends a new 6-digit OTP to user email for registration. Previous OTPs will be invalidated. POST /auth/register/resend-otp */
export async function authControllerResendRegisterOtp(
  // Param type generated by superposition
  params: API.AuthControllerResendRegisterOtpParams,
  options?: { [key: string]: any }
) {
  return request<API.OTPResponseResponseDto>("/auth/register/resend-otp", {
    method: "POST",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Send OTP for registration Sends a 6-digit OTP to user email for account verification during registration. OTP expires in 5 minutes. POST /auth/register/send-otp */
export async function authControllerSendRegisterOtp(
  body: API.RegisterRequest,
  options?: { [key: string]: any }
) {
  return request<API.OTPResponseResponseDto>("/auth/register/send-otp", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Complete registration with OTP verification Creates a new user account after OTP verification. Returns JWT tokens for immediate login. POST /auth/register/verify */
export async function authControllerRegisterWithOtp(
  body: API.RegisterWithOtpRequest,
  options?: { [key: string]: any }
) {
  return request<any>("/auth/register/verify", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Resend OTP Resends OTP to user's email. Previous OTPs will be invalidated. POST /auth/resend-otp */
export async function authControllerResendOtp(
  // Param type generated by superposition
  params: API.AuthControllerResendOtpParams,
  options?: { [key: string]: any }
) {
  return request<API.OTPResponseResponseDto>("/auth/resend-otp", {
    method: "POST",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Reset password with OTP Resets user password using verified OTP. The OTP will be marked as used after successful reset. POST /auth/reset-password */
export async function authControllerResetPassword(
  body: API.ResetPasswordRequest,
  options?: { [key: string]: any }
) {
  return request<any>("/auth/reset-password", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Social login with Google/Facebook Login or register using Google/Facebook OAuth. Automatically creates account if user does not exist. POST /auth/social-login */
export async function authControllerSocialLogin(
  body: API.SocialLoginRequest,
  options?: { [key: string]: any }
) {
  return request<API.LoginResponseResponseDto>("/auth/social-login", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}
