// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all categories GET /categories */
export async function categoryControllerFindAll(
  // Param type generated by superposition
  params: API.CategoryControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.CategoryDtoPaginatedResponseDto>("/categories", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create new category POST /categories */
export async function categoryControllerCreate(
  body: API.CreateCategoryDto,
  options?: { [key: string]: any }
) {
  return request<API.CategoryDtoResponseDto>("/categories", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get category by ID GET /categories/${param0} */
export async function categoryControllerFindOne(
  // Param type generated by superposition
  params: API.CategoryControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.CategoryDtoResponseDto>(`/categories/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update category PUT /categories/${param0} */
export async function categoryControllerUpdate(
  // Param type generated by superposition
  params: API.CategoryControllerUpdateParams,
  body: API.UpdateCategoryDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.CategoryDtoResponseDto>(`/categories/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete category DELETE /categories/${param0} */
export async function categoryControllerRemove(
  // Param type generated by superposition
  params: API.CategoryControllerRemoveParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/categories/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get all categories with TV series count GET /categories/with-count */
export async function categoryControllerFindAllWithCount(options?: {
  [key: string]: any;
}) {
  return request<API.TVSeriesCategoryPaginatedResponseDto>(
    "/categories/with-count",
    {
      method: "GET",
      ...(options || {}),
    }
  );
}
