// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all categories GET /api/v1/categories */
export async function categoriesControllerGetCategories(
  // Param type generated by superposition
  params: API.CategoriesControllerGetCategoriesParams,
  options?: { [key: string]: any }
) {
  return request<API.CategoryDtoPaginatedResponseDto>("/api/v1/categories", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create new category POST /api/v1/categories */
export async function categoriesControllerCreateCategory(
  body: API.CreateCategoryDto,
  options?: { [key: string]: any }
) {
  return request<API.CategoryDtoResponseDto>("/api/v1/categories", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get category by ID GET /api/v1/categories/${param0} */
export async function categoriesControllerGetCategoryById(
  // Param type generated by superposition
  params: API.CategoriesControllerGetCategoryByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.CategoryDtoResponseDto>(`/api/v1/categories/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update category PUT /api/v1/categories/${param0} */
export async function categoriesControllerUpdateCategory(
  // Param type generated by superposition
  params: API.CategoriesControllerUpdateCategoryParams,
  body: API.UpdateCategoryDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.CategoryDtoResponseDto>(`/api/v1/categories/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete category DELETE /api/v1/categories/${param0} */
export async function categoriesControllerDeleteCategory(
  // Param type generated by superposition
  params: API.CategoriesControllerDeleteCategoryParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/categories/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Search categories GET /api/v1/categories/search */
export async function categoriesControllerSearchCategories(
  // Param type generated by superposition
  params: API.CategoriesControllerSearchCategoriesParams,
  options?: { [key: string]: any }
) {
  return request<API.CategoryDtoResponseDto>("/api/v1/categories/search", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Get all categories with TV series count GET /api/v1/categories/tv-series-count */
export async function categoriesControllerGetCategoriesWithTvSeriesCount(options?: {
  [key: string]: any;
}) {
  return request<API.TVSeriesCategoryResponseDto>(
    "/api/v1/categories/tv-series-count",
    {
      method: "GET",
      ...(options || {}),
    }
  );
}
