// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get movies and TV series with filters GET /contents */
export async function contentControllerFindAll(
  // Param type generated by superposition
  params: API.ContentControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.ContentDtoResponseDto>("/contents", {
    method: "GET",
    params: {
      // sortBy has a default value: date
      sortBy: "date",
      // order has a default value: DESC
      order: "DESC",
      // page has a default value: 1
      page: "1",
      // limit has a default value: 10
      limit: "10",
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create new content (movie or TV series) POST /contents */
export async function contentControllerCreate(
  body: API.CreateContentDto,
  options?: { [key: string]: any }
) {
  return request<API.ContentDtoResponseDto>("/contents", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get content by ID GET /contents/${param0} */
export async function contentControllerFindOne(
  // Param type generated by superposition
  params: API.ContentControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ContentDtoResponseDto>(`/contents/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update content and its relationships PUT /contents/${param0} */
export async function contentControllerUpdate(
  // Param type generated by superposition
  params: API.ContentControllerUpdateParams,
  body: API.UpdateContentDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ContentDtoResponseDto>(`/contents/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete content and its relationships DELETE /contents/${param0} */
export async function contentControllerDelete(
  // Param type generated by superposition
  params: API.ContentControllerDeleteParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/contents/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Increase view count for content POST /contents/${param0}/increase-view */
export async function contentControllerIncreaseView(
  // Param type generated by superposition
  params: API.ContentControllerIncreaseViewParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/contents/${param0}/increase-view`, {
    method: "POST",
    params: { ...queryParams },
    ...(options || {}),
  });
}
