// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get movies and TV series with filters GET /api/v1/contents */
export async function contentsControllerGetContents(
  // Param type generated by superposition
  params: API.ContentsControllerGetContentsParams,
  options?: { [key: string]: any }
) {
  return request<API.ObjectResponseDto>("/api/v1/contents", {
    method: "GET",
    params: {
      // sortBy has a default value: date
      sortBy: "date",
      // order has a default value: DESC
      order: "DESC",
      // page has a default value: 1
      page: "1",
      // limit has a default value: 10
      limit: "10",
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create new content (movie or TV series) POST /api/v1/contents */
export async function contentsControllerCreateContent(
  body: API.CreateContentDto,
  options?: { [key: string]: any }
) {
  return request<API.ContentDtoResponseDto>("/api/v1/contents", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get content by ID GET /api/v1/contents/${param0} */
export async function contentsControllerGetContentById(
  // Param type generated by superposition
  params: API.ContentsControllerGetContentByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ContentDtoResponseDto>(`/api/v1/contents/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update content and its relationships PUT /api/v1/contents/${param0} */
export async function contentsControllerUpdateContent(
  // Param type generated by superposition
  params: API.ContentsControllerUpdateContentParams,
  body: API.UpdateContentDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ContentDtoResponseDto>(`/api/v1/contents/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete content and its relationships DELETE /api/v1/contents/${param0} */
export async function contentsControllerDeleteContent(
  // Param type generated by superposition
  params: API.ContentsControllerDeleteContentParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/contents/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Increase view count for a content PATCH /api/v1/contents/${param0}/view */
export async function contentsControllerIncreaseViewCount(
  // Param type generated by superposition
  params: API.ContentsControllerIncreaseViewCountParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.BooleanResponseDto>(`/api/v1/contents/${param0}/view`, {
    method: "PATCH",
    params: { ...queryParams },
    ...(options || {}),
  });
}
