// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all directors GET /api/v1/directors */
export async function directorsControllerGetDirectors(
  // Param type generated by superposition
  params: API.DirectorsControllerGetDirectorsParams,
  options?: { [key: string]: any }
) {
  return request<any>("/api/v1/directors", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create a new director POST /api/v1/directors */
export async function directorsControllerCreateDirector(
  body: API.CreateDirectorDto,
  options?: { [key: string]: any }
) {
  return request<any>("/api/v1/directors", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get a director by ID with all contents GET /api/v1/directors/${param0} */
export async function directorsControllerGetDirectorById(
  // Param type generated by superposition
  params: API.DirectorsControllerGetDirectorByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/directors/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update a director PUT /api/v1/directors/${param0} */
export async function directorsControllerUpdateDirector(
  // Param type generated by superposition
  params: API.DirectorsControllerUpdateDirectorParams,
  body: API.UpdateDirectorDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/directors/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete a director DELETE /api/v1/directors/${param0} */
export async function directorsControllerDeleteDirector(
  // Param type generated by superposition
  params: API.DirectorsControllerDeleteDirectorParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/directors/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Search directors GET /api/v1/directors/search */
export async function directorsControllerSearchDirectors(
  // Param type generated by superposition
  params: API.DirectorsControllerSearchDirectorsParams,
  options?: { [key: string]: any }
) {
  return request<any>("/api/v1/directors/search", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}
