// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all directors GET /directors */
export async function directorControllerFindAll(
  // Param type generated by superposition
  params: API.DirectorControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<any>("/directors", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create a new director POST /directors */
export async function directorControllerCreate(
  body: API.CreateDirectorDto,
  options?: { [key: string]: any }
) {
  return request<any>("/directors", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get a director by ID with all contents GET /directors/${param0} */
export async function directorControllerFindOne(
  // Param type generated by superposition
  params: API.DirectorControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/directors/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update a director PUT /directors/${param0} */
export async function directorControllerUpdate(
  // Param type generated by superposition
  params: API.DirectorControllerUpdateParams,
  body: API.UpdateDirectorDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/directors/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete a director DELETE /directors/${param0} */
export async function directorControllerRemove(
  // Param type generated by superposition
  params: API.DirectorControllerRemoveParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/directors/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}
