// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all reviews GET /episode-reviews */
export async function episodeReviewControllerFindAll(
  // Param type generated by superposition
  params: API.EpisodeReviewControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.ReviewDtoPaginatedResponseDto>("/episode-reviews", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Create a new review POST /episode-reviews */
export async function episodeReviewControllerCreateReview(
  body: API.CreateEpisodeReviewDto,
  options?: { [key: string]: any }
) {
  return request<API.EpisodeReviewDtoResponseDto>("/episode-reviews", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get a review by ID GET /episode-reviews/${param0} */
export async function episodeReviewControllerFindOne(
  // Param type generated by superposition
  params: API.EpisodeReviewControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ReviewDtoResponseDto>(`/episode-reviews/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Update a review by ID PUT /episode-reviews/${param0} */
export async function episodeReviewControllerUpdateReview(
  // Param type generated by superposition
  params: API.EpisodeReviewControllerUpdateReviewParams,
  body: API.UpdateEpisodeReviewDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.EpisodeReviewDtoResponseDto>(
    `/episode-reviews/${param0}`,
    {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      params: { ...queryParams },
      data: body,
      ...(options || {}),
    }
  );
}

/** Delete a review by ID DELETE /episode-reviews/${param0} */
export async function episodeReviewControllerDeleteReview(
  // Param type generated by superposition
  params: API.EpisodeReviewControllerDeleteReviewParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ReviewDtoResponseDto>(`/episode-reviews/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get reviews by user ID GET /episode-reviews/by-user */
export async function episodeReviewControllerFindReviewsByUserId(
  // Param type generated by superposition
  params: API.EpisodeReviewControllerFindReviewsByUserIdParams,
  options?: { [key: string]: any }
) {
  return request<API.EpisodeReviewDtoPaginatedResponseDto>(
    "/episode-reviews/by-user",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Check if user is the owner of a review GET /episode-reviews/check-owner/${param0} */
export async function episodeReviewControllerCheckReviewOwner(
  // Param type generated by superposition
  params: API.EpisodeReviewControllerCheckReviewOwnerParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/episode-reviews/check-owner/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get reviews for a specific episode by episode ID GET /episode-reviews/for-episode/${param0} */
export async function episodeReviewControllerGetReviewForEpisode(
  // Param type generated by superposition
  params: API.EpisodeReviewControllerGetReviewForEpisodeParams,
  options?: { [key: string]: any }
) {
  const { episodeId: param0, ...queryParams } = params;
  return request<API.EpisodeReviewDtoPaginatedResponseDto>(
    `/episode-reviews/for-episode/${param0}`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}
