// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get episode detail by ID GET /api/v1/episodes/${param0} */
export async function episodesControllerGetEpisodeById(
  // Param type generated by superposition
  params: API.EpisodesControllerGetEpisodeByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.EpisodeDto>(`/api/v1/episodes/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}
