// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get user favorites GET /favorites */
export async function favoriteControllerGetFavorites(options?: {
  [key: string]: any;
}) {
  return request<any>("/favorites", {
    method: "GET",
    ...(options || {}),
  });
}

/** Add content to favorites POST /favorites */
export async function favoriteControllerCreateFavorite(
  body: API.CreateFavoriteDto,
  options?: { [key: string]: any }
) {
  return request<API.FavoriteContentDtoResponseDto>("/favorites", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Remove multiple contents from favorites DELETE /favorites */
export async function favoriteControllerRemoveArrayFavorite(
  body: API.DeleteFavoriteDto,
  options?: { [key: string]: any }
) {
  return request<any>("/favorites", {
    method: "DELETE",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Remove content from favorites DELETE /favorites/${param0} */
export async function favoriteControllerRemoveFavorite(
  // Param type generated by superposition
  params: API.FavoriteControllerRemoveFavoriteParams,
  options?: { [key: string]: any }
) {
  const { contentId: param0, ...queryParams } = params;
  return request<any>(`/favorites/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get favorite status for content (logged in or guest) GET /favorites/${param0}/status */
export async function favoriteControllerGetFavoriteStatus(
  // Param type generated by superposition
  params: API.FavoriteControllerGetFavoriteStatusParams,
  options?: { [key: string]: any }
) {
  const { contentId: param0, ...queryParams } = params;
  return request<API.FavoriteContentDtoResponseDto>(
    `/favorites/${param0}/status`,
    {
      method: "GET",
      params: { ...queryParams },
      ...(options || {}),
    }
  );
}
