// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all movies GET /api/v1/movies */
export async function moviesControllerGetMovies(
  // Param type generated by superposition
  params: API.MoviesControllerGetMoviesParams,
  options?: { [key: string]: any }
) {
  return request<API.MovieDtoPaginatedResponseDto>("/api/v1/movies", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create new movie POST /api/v1/movies */
export async function moviesControllerCreateMovie(
  body: API.CreateMovieDto,
  options?: { [key: string]: any }
) {
  return request<API.MovieDtoResponseDto>("/api/v1/movies", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get movie by ID GET /api/v1/movies/${param0} */
export async function moviesControllerGetMovieById(
  // Param type generated by superposition
  params: API.MoviesControllerGetMovieByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.MovieDtoResponseDto>(`/api/v1/movies/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update movie PUT /api/v1/movies/${param0} */
export async function moviesControllerUpdateMovie(
  // Param type generated by superposition
  params: API.MoviesControllerUpdateMovieParams,
  body: API.UpdateMovieDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.MovieDtoResponseDto>(`/api/v1/movies/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete movie DELETE /api/v1/movies/${param0} */
export async function moviesControllerDeleteMovie(
  // Param type generated by superposition
  params: API.MoviesControllerDeleteMovieParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/movies/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get movie recommendations by movie ID GET /api/v1/movies/${param0}/recommendations */
export async function moviesControllerGetRecommendationsByMovieId(
  // Param type generated by superposition
  params: API.MoviesControllerGetRecommendationsByMovieIdParams,
  options?: { [key: string]: any }
) {
  const { movieId: param0, ...queryParams } = params;
  return request<API.MovieDtoPaginatedResponseDto>(
    `/api/v1/movies/${param0}/recommendations`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}

/** Get movies by category GET /api/v1/movies/category/${param0} */
export async function moviesControllerGetMoviesByCategory(
  // Param type generated by superposition
  params: API.MoviesControllerGetMoviesByCategoryParams,
  options?: { [key: string]: any }
) {
  const { categoryId: param0, ...queryParams } = params;
  return request<API.MovieDtoPaginatedResponseDto>(
    `/api/v1/movies/category/${param0}`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}

/** Get new release movies GET /api/v1/movies/new-releases */
export async function moviesControllerGetNewReleaseMovies(
  // Param type generated by superposition
  params: API.MoviesControllerGetNewReleaseMoviesParams,
  options?: { [key: string]: any }
) {
  return request<API.MovieDtoPaginatedResponseDto>(
    "/api/v1/movies/new-releases",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get trending movies GET /api/v1/movies/trending */
export async function moviesControllerGetTrendingMovies(
  // Param type generated by superposition
  params: API.MoviesControllerGetTrendingMoviesParams,
  options?: { [key: string]: any }
) {
  return request<API.MovieDtoPaginatedResponseDto>("/api/v1/movies/trending", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}
