// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all movies GET /movies */
export async function movieControllerFindAll(
  // Param type generated by superposition
  params: API.MovieControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.MovieDtoPaginatedResponseDto>("/movies", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create new movie POST /movies */
export async function movieControllerCreate(
  body: API.CreateMovieDto,
  options?: { [key: string]: any }
) {
  return request<API.MovieDtoResponseDto>("/movies", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get movie by ID GET /movies/${param0} */
export async function movieControllerFindOne(
  // Param type generated by superposition
  params: API.MovieControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.MovieDtoResponseDto>(`/movies/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update movie PUT /movies/${param0} */
export async function movieControllerUpdate(
  // Param type generated by superposition
  params: API.MovieControllerUpdateParams,
  body: API.UpdateMovieDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.MovieDtoResponseDto>(`/movies/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete movie DELETE /movies/${param0} */
export async function movieControllerDelete(
  // Param type generated by superposition
  params: API.MovieControllerDeleteParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/movies/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get movie recommendations by movie ID GET /movies/${param0}/recommendations */
export async function movieControllerGetRecommendationsByMovieId(
  // Param type generated by superposition
  params: API.MovieControllerGetRecommendationsByMovieIdParams,
  options?: { [key: string]: any }
) {
  const { movieId: param0, ...queryParams } = params;
  return request<API.MovieDtoPaginatedResponseDto>(
    `/movies/${param0}/recommendations`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}

/** Get movies by category GET /movies/category/${param0} */
export async function movieControllerGetMoviesByCategory(
  // Param type generated by superposition
  params: API.MovieControllerGetMoviesByCategoryParams,
  options?: { [key: string]: any }
) {
  const { categoryId: param0, ...queryParams } = params;
  return request<API.MovieDtoPaginatedResponseDto>(
    `/movies/category/${param0}`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}

/** Get new release movies GET /movies/new-releases */
export async function movieControllerGetNewReleaseMovies(
  // Param type generated by superposition
  params: API.MovieControllerGetNewReleaseMoviesParams,
  options?: { [key: string]: any }
) {
  return request<API.MovieDtoPaginatedResponseDto>("/movies/new-releases", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Get trending movies GET /movies/trending-movies */
export async function movieControllerGetTrendingMovies(
  // Param type generated by superposition
  params: API.MovieControllerGetTrendingMoviesParams,
  options?: { [key: string]: any }
) {
  return request<API.MovieDtoPaginatedResponseDto>("/movies/trending-movies", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}
