// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all news GET /api/v1/news */
export async function newsControllerGetNews(
  // Param type generated by superposition
  params: API.NewsControllerGetNewsParams,
  options?: { [key: string]: any }
) {
  return request<API.NewsDtoPaginatedResponseDto>("/api/v1/news", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create new news POST /api/v1/news */
export async function newsControllerCreateNews(
  body: API.CreateNewsBySessionDto,
  options?: { [key: string]: any }
) {
  return request<API.NewsDtoResponseDto>("/api/v1/news", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get news by ID GET /api/v1/news/${param0} */
export async function newsControllerGetNewsById(
  // Param type generated by superposition
  params: API.NewsControllerGetNewsByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.NewsDtoResponseDto>(`/api/v1/news/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update news PUT /api/v1/news/${param0} */
export async function newsControllerUpdateNews(
  // Param type generated by superposition
  params: API.NewsControllerUpdateNewsParams,
  body: API.UpdateNewsDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.NewsDtoResponseDto>(`/api/v1/news/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete news DELETE /api/v1/news/${param0} */
export async function newsControllerDeleteNews(
  // Param type generated by superposition
  params: API.NewsControllerDeleteNewsParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/news/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get related news by news ID GET /api/v1/news/${param0}/recommendations */
export async function newsControllerGetRelatedNews(
  // Param type generated by superposition
  params: API.NewsControllerGetRelatedNewsParams,
  options?: { [key: string]: any }
) {
  const { newsId: param0, ...queryParams } = params;
  return request<API.NewsDtoPaginatedResponseDto>(
    `/api/v1/news/${param0}/recommendations`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}
