// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all news GET /news */
export async function newsControllerFindAll(
  // Param type generated by superposition
  params: API.NewsControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.NewsDtoPaginatedResponseDto>("/news", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create a new news POST /news */
export async function newsControllerCreate(
  body: API.CreateNewsDto,
  options?: { [key: string]: any }
) {
  return request<API.NewsDtoResponseDto>("/news", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get news by ID GET /news/${param0} */
export async function newsControllerFindOne(
  // Param type generated by superposition
  params: API.NewsControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.NewsDtoResponseDto>(`/news/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update an existing news PUT /news/${param0} */
export async function newsControllerUpdate(
  // Param type generated by superposition
  params: API.NewsControllerUpdateParams,
  body: API.UpdateNewsDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.NewsDtoResponseDto>(`/news/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete a news DELETE /news/${param0} */
export async function newsControllerDelete(
  // Param type generated by superposition
  params: API.NewsControllerDeleteParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/news/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get related news by ID GET /news/${param0}/related */
export async function newsControllerFindNewsRelated(
  // Param type generated by superposition
  params: API.NewsControllerFindNewsRelatedParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.NewsDtoPaginatedResponseDto>(`/news/${param0}/related`, {
    method: "GET",
    params: {
      ...queryParams,
    },
    ...(options || {}),
  });
}
