// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get payment detail by ID Returns the full detail of a single payment record owned by the authenticated user. GET /api/v1/payments/${param0} */
export async function paymentControllerGetById(
  // Param type generated by superposition
  params: API.PaymentControllerGetByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.PaymentDetailDtoResponseDto>(
    `/api/v1/payments/${param0}`,
    {
      method: "GET",
      params: { ...queryParams },
      ...(options || {}),
    }
  );
}

/** Get paginated payment history Returns a paginated list of all payments made by the authenticated user. GET /api/v1/payments/history */
export async function paymentControllerGetHistory(
  // Param type generated by superposition
  params: API.PaymentControllerGetHistoryParams,
  options?: { [key: string]: any }
) {
  return request<API.PaymentDetailDtoPaginatedResponseDto>(
    "/api/v1/payments/history",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Initiate subscription payment via VNPAY Creates a pending payment record and returns the VNPAY checkout URL. Redirect the user to `paymentUrl` to complete the payment. After payment, VNPAY calls the IPN webhook which triggers the subscription saga. POST /api/v1/payments/subscribe */
export async function paymentControllerInitiateSubscription(
  body: API.InitiatePaymentDto,
  options?: { [key: string]: any }
) {
  return request<API.InitiatePaymentResponseDtoResponseDto>(
    "/api/v1/payments/subscribe",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      data: body,
      ...(options || {}),
    }
  );
}

/** VNPAY IPN webhook callback Called by VNPAY servers after a payment is processed. Validates the HMAC signature, updates payment status, and triggers the subscription saga. **Do not call this endpoint manually.** Returns raw `{ RspCode, Message }` as required by VNPAY. GET /api/v1/payments/vnpay-ipn */
export async function paymentControllerVnpayIpnGet(options?: {
  [key: string]: any;
}) {
  return request<API.VnpayIpnResponseDto>("/api/v1/payments/vnpay-ipn", {
    method: "GET",
    ...(options || {}),
  });
}

/** VNPAY IPN webhook callback Called by VNPAY servers after a payment is processed. Validates the HMAC signature, updates payment status, and triggers the subscription saga. **Do not call this endpoint manually.** Returns raw `{ RspCode, Message }` as required by VNPAY. PUT /api/v1/payments/vnpay-ipn */
export async function paymentControllerVnpayIpnPut(options?: {
  [key: string]: any;
}) {
  return request<API.VnpayIpnResponseDto>("/api/v1/payments/vnpay-ipn", {
    method: "PUT",
    ...(options || {}),
  });
}

/** VNPAY IPN webhook callback Called by VNPAY servers after a payment is processed. Validates the HMAC signature, updates payment status, and triggers the subscription saga. **Do not call this endpoint manually.** Returns raw `{ RspCode, Message }` as required by VNPAY. POST /api/v1/payments/vnpay-ipn */
export async function paymentControllerVnpayIpnPost(options?: {
  [key: string]: any;
}) {
  return request<API.VnpayIpnResponseDto>("/api/v1/payments/vnpay-ipn", {
    method: "POST",
    ...(options || {}),
  });
}

/** VNPAY IPN webhook callback Called by VNPAY servers after a payment is processed. Validates the HMAC signature, updates payment status, and triggers the subscription saga. **Do not call this endpoint manually.** Returns raw `{ RspCode, Message }` as required by VNPAY. DELETE /api/v1/payments/vnpay-ipn */
export async function paymentControllerVnpayIpnDelete(options?: {
  [key: string]: any;
}) {
  return request<API.VnpayIpnResponseDto>("/api/v1/payments/vnpay-ipn", {
    method: "DELETE",
    ...(options || {}),
  });
}

/** VNPAY IPN webhook callback Called by VNPAY servers after a payment is processed. Validates the HMAC signature, updates payment status, and triggers the subscription saga. **Do not call this endpoint manually.** Returns raw `{ RspCode, Message }` as required by VNPAY. PATCH /api/v1/payments/vnpay-ipn */
export async function paymentControllerVnpayIpnPatch(options?: {
  [key: string]: any;
}) {
  return request<API.VnpayIpnResponseDto>("/api/v1/payments/vnpay-ipn", {
    method: "PATCH",
    ...(options || {}),
  });
}

/** VNPAY return redirect VNPAY redirects the user here after completing payment. This endpoint immediately redirects to the frontend payment result page. GET /api/v1/payments/vnpay-return */
export async function paymentControllerVnpayReturn(options?: {
  [key: string]: any;
}) {
  return request<any>("/api/v1/payments/vnpay-return", {
    method: "GET",
    ...(options || {}),
  });
}
