// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get personalized recommendations for the logged-in user Calls AI recommendation engine (FastAPI) to get personalized movie & TV series suggestions. Fallback to trending content if the AI service is unavailable. GET /api/v1/recommendations */
export async function recommendationsControllerGetRecommendations(
  // Param type generated by superposition
  params: API.RecommendationsControllerGetRecommendationsParams,
  options?: { [key: string]: any }
) {
  return request<API.RecommendationResponseDataDtoResponseDto>(
    "/api/v1/recommendations",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}
