// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all reports (Admin only) GET /reports */
export async function reportControllerFindAll(
  // Param type generated by superposition
  params: API.ReportControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.ReportDtoPaginatedResponseDto>("/reports", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Report a review or episode review POST /reports */
export async function reportControllerCreateReport(
  body: API.CreateReportDto,
  options?: { [key: string]: any }
) {
  return request<API.ReportDtoResponseDto>("/reports", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get a report by ID (Admin only) GET /reports/${param0} */
export async function reportControllerFindOne(
  // Param type generated by superposition
  params: API.ReportControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ReportDtoResponseDto>(`/reports/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Delete a report (Admin only) DELETE /reports/${param0} */
export async function reportControllerDeleteReport(
  // Param type generated by superposition
  params: API.ReportControllerDeleteReportParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/reports/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Approve a review or episode review (Admin only) PUT /reports/approve/${param0}/${param1} */
export async function reportControllerApproveItem(
  // Param type generated by superposition
  params: API.ReportControllerApproveItemParams,
  options?: { [key: string]: any }
) {
  const { type: param0, id: param1, ...queryParams } = params;
  return request<any>(`/reports/approve/${param0}/${param1}`, {
    method: "PUT",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Ban a review or episode review (Admin only) PUT /reports/ban/${param0}/${param1} */
export async function reportControllerBanItem(
  // Param type generated by superposition
  params: API.ReportControllerBanItemParams,
  options?: { [key: string]: any }
) {
  const { type: param0, id: param1, ...queryParams } = params;
  return request<any>(`/reports/ban/${param0}/${param1}`, {
    method: "PUT",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Reject a review or episode review (Admin only) PUT /reports/reject/${param0}/${param1} */
export async function reportControllerRejectItem(
  // Param type generated by superposition
  params: API.ReportControllerRejectItemParams,
  options?: { [key: string]: any }
) {
  const { type: param0, id: param1, ...queryParams } = params;
  return request<any>(`/reports/reject/${param0}/${param1}`, {
    method: "PUT",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Unban a review or episode review (Admin only) PUT /reports/unban/${param0}/${param1} */
export async function reportControllerUnbanItem(
  // Param type generated by superposition
  params: API.ReportControllerUnbanItemParams,
  options?: { [key: string]: any }
) {
  const { type: param0, id: param1, ...queryParams } = params;
  return request<any>(`/reports/unban/${param0}/${param1}`, {
    method: "PUT",
    params: { ...queryParams },
    ...(options || {}),
  });
}
