// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all reports (Admin only) GET /api/v1/reports */
export async function reportControllerFindAll(
  // Param type generated by superposition
  params: API.ReportControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.ReportDtoPaginatedResponseDto>("/api/v1/reports", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Create a new report POST /api/v1/reports */
export async function reportControllerCreate(
  body: API.CreateReportDto,
  options?: { [key: string]: any }
) {
  return request<API.ReportDtoResponseDto>("/api/v1/reports", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get a report by ID (Admin only) GET /api/v1/reports/${param0} */
export async function reportControllerFindOne(
  // Param type generated by superposition
  params: API.ReportControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ReportDtoResponseDto>(`/api/v1/reports/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Delete a report (Admin only) DELETE /api/v1/reports/${param0} */
export async function reportControllerDelete(
  // Param type generated by superposition
  params: API.ReportControllerDeleteParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/reports/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Approve a report and ban the item (Admin only) POST /api/v1/reports/${param0}/approve */
export async function reportControllerApprove(
  // Param type generated by superposition
  params: API.ReportControllerApproveParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/reports/${param0}/approve`, {
    method: "POST",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Reject a report (Admin only) POST /api/v1/reports/${param0}/reject */
export async function reportControllerReject(
  // Param type generated by superposition
  params: API.ReportControllerRejectParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/reports/${param0}/reject`, {
    method: "POST",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Directly ban an item (Admin only) POST /api/v1/reports/ban */
export async function reportControllerBan(
  body: API.BanItemDto,
  options?: { [key: string]: any }
) {
  return request<any>("/api/v1/reports/ban", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Unban an item (Admin only) POST /api/v1/reports/unban */
export async function reportControllerUnban(
  body: API.BanItemDto,
  options?: { [key: string]: any }
) {
  return request<any>("/api/v1/reports/unban", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}
