// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all review replies (Admin only) GET /api/v1/review-replies */
export async function reviewReplyControllerFindAll(
  // Param type generated by superposition
  params: API.ReviewReplyControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.ReviewReplyDtoPaginatedResponseDto>(
    "/api/v1/review-replies",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Create a new reply POST /api/v1/review-replies */
export async function reviewReplyControllerCreateReply(
  body: API.CreateReviewReplyDto,
  options?: { [key: string]: any }
) {
  return request<API.ReviewReplyDtoResponseDto>("/api/v1/review-replies", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get a reply by ID GET /api/v1/review-replies/${param0} */
export async function reviewReplyControllerFindOne(
  // Param type generated by superposition
  params: API.ReviewReplyControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ReviewReplyDtoResponseDto>(
    `/api/v1/review-replies/${param0}`,
    {
      method: "GET",
      params: { ...queryParams },
      ...(options || {}),
    }
  );
}

/** Update a reply by ID PUT /api/v1/review-replies/${param0} */
export async function reviewReplyControllerUpdateReply(
  // Param type generated by superposition
  params: API.ReviewReplyControllerUpdateReplyParams,
  body: API.UpdateReviewReplyDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ReviewReplyDtoResponseDto>(
    `/api/v1/review-replies/${param0}`,
    {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      params: { ...queryParams },
      data: body,
      ...(options || {}),
    }
  );
}

/** Delete a reply by ID DELETE /api/v1/review-replies/${param0} */
export async function reviewReplyControllerDeleteReply(
  // Param type generated by superposition
  params: API.ReviewReplyControllerDeleteReplyParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/review-replies/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get replies by user ID GET /api/v1/review-replies/by-user */
export async function reviewReplyControllerFindRepliesByUserId(
  // Param type generated by superposition
  params: API.ReviewReplyControllerFindRepliesByUserIdParams,
  options?: { [key: string]: any }
) {
  return request<API.ReviewReplyDtoPaginatedResponseDto>(
    "/api/v1/review-replies/by-user",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Check if user is the owner of a reply GET /api/v1/review-replies/check-owner/${param0} */
export async function reviewReplyControllerCheckReplyOwner(
  // Param type generated by superposition
  params: API.ReviewReplyControllerCheckReplyOwnerParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/review-replies/check-owner/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get total reply count for an episode review GET /api/v1/review-replies/count/episode-review/${param0} */
export async function reviewReplyControllerGetReplyCountForEpisodeReview(
  // Param type generated by superposition
  params: API.ReviewReplyControllerGetReplyCountForEpisodeReviewParams,
  options?: { [key: string]: any }
) {
  const { episodeReviewId: param0, ...queryParams } = params;
  return request<{
    episodeReviewId?: string;
    replyCount?: number;
    hasReplies?: boolean;
  }>(`/api/v1/review-replies/count/episode-review/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get direct child reply count for a reply GET /api/v1/review-replies/count/reply/${param0} */
export async function reviewReplyControllerGetReplyCountForReply(
  // Param type generated by superposition
  params: API.ReviewReplyControllerGetReplyCountForReplyParams,
  options?: { [key: string]: any }
) {
  const { replyId: param0, ...queryParams } = params;
  return request<{
    replyId?: string;
    replyCount?: number;
    hasReplies?: boolean;
  }>(`/api/v1/review-replies/count/reply/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get total reply count for a review GET /api/v1/review-replies/count/review/${param0} */
export async function reviewReplyControllerGetReplyCountForReview(
  // Param type generated by superposition
  params: API.ReviewReplyControllerGetReplyCountForReviewParams,
  options?: { [key: string]: any }
) {
  const { reviewId: param0, ...queryParams } = params;
  return request<{
    reviewId?: string;
    replyCount?: number;
    hasReplies?: boolean;
  }>(`/api/v1/review-replies/count/review/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get replies for a specific episode review GET /api/v1/review-replies/for-episode-review/${param0} */
export async function reviewReplyControllerGetRepliesForEpisodeReview(
  // Param type generated by superposition
  params: API.ReviewReplyControllerGetRepliesForEpisodeReviewParams,
  options?: { [key: string]: any }
) {
  const { episodeReviewId: param0, ...queryParams } = params;
  return request<API.ReviewReplyDtoPaginatedResponseDto>(
    `/api/v1/review-replies/for-episode-review/${param0}`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}

/** Get replies for a specific review GET /api/v1/review-replies/for-review/${param0} */
export async function reviewReplyControllerGetRepliesForReview(
  // Param type generated by superposition
  params: API.ReviewReplyControllerGetRepliesForReviewParams,
  options?: { [key: string]: any }
) {
  const { reviewId: param0, ...queryParams } = params;
  return request<API.ReviewReplyDtoPaginatedResponseDto>(
    `/api/v1/review-replies/for-review/${param0}`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}
