// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all reviews GET /reviews */
export async function reviewControllerFindAll(
  // Param type generated by superposition
  params: API.ReviewControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.ReviewDtoPaginatedResponseDto>("/reviews", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Create a new review POST /reviews */
export async function reviewControllerCreateReview(
  body: API.CreateReviewDto,
  options?: { [key: string]: any }
) {
  return request<API.ReviewDtoResponseDto>("/reviews", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get a review by ID GET /reviews/${param0} */
export async function reviewControllerFindOne(
  // Param type generated by superposition
  params: API.ReviewControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ReviewDtoResponseDto>(`/reviews/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Update a review by ID PUT /reviews/${param0} */
export async function reviewControllerUpdateReview(
  // Param type generated by superposition
  params: API.ReviewControllerUpdateReviewParams,
  body: API.UpdateReviewDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ReviewDtoResponseDto>(`/reviews/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** Delete a review by ID DELETE /reviews/${param0} */
export async function reviewControllerDeleteReview(
  // Param type generated by superposition
  params: API.ReviewControllerDeleteReviewParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.ReviewDtoResponseDto>(`/reviews/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get reviews by user ID GET /reviews/by-user */
export async function reviewControllerFindReviewsByUserId(
  // Param type generated by superposition
  params: API.ReviewControllerFindReviewsByUserIdParams,
  options?: { [key: string]: any }
) {
  return request<API.ReviewDtoPaginatedResponseDto>("/reviews/by-user", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Check if user is the owner of a review GET /reviews/check-owner/${param0} */
export async function reviewControllerCheckReviewOwner(
  // Param type generated by superposition
  params: API.ReviewControllerCheckReviewOwnerParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/reviews/check-owner/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get reviews for a specific content by content ID GET /reviews/for-content/${param0} */
export async function reviewControllerGetReviewForContent(
  // Param type generated by superposition
  params: API.ReviewControllerGetReviewForContentParams,
  options?: { [key: string]: any }
) {
  const { contentId: param0, ...queryParams } = params;
  return request<API.ReviewDtoPaginatedResponseDto>(
    `/reviews/for-content/${param0}`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}
