// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Generate CloudFront signed cookies for video access GET /api/v1/videos/${param0}/access */
export async function streamingControllerGetFileAccess(
  // Param type generated by superposition
  params: API.StreamingControllerGetFileAccessParams,
  options?: { [key: string]: any }
) {
  const { s3Key: param0, ...queryParams } = params;
  return request<any>(`/api/v1/videos/${param0}/access`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get DRM key info (keyId) for a video GET /api/v1/videos/${param0}/drm-info */
export async function streamingControllerGetDrmKeyInfo(
  // Param type generated by superposition
  params: API.StreamingControllerGetDrmKeyInfoParams,
  options?: { [key: string]: any }
) {
  const { videoId: param0, ...queryParams } = params;
  return request<any>(`/api/v1/videos/${param0}/drm-info`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get signed DASH manifest URL for DRM-protected video GET /api/v1/videos/${param0}/manifest */
export async function streamingControllerGetManifestUrl(
  // Param type generated by superposition
  params: API.StreamingControllerGetManifestUrlParams,
  options?: { [key: string]: any }
) {
  const { videoId: param0, ...queryParams } = params;
  return request<any>(`/api/v1/videos/${param0}/manifest`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Upload video for HLS encoding POST /api/v1/videos/upload */
export async function streamingControllerUploadVideo(
  body: {},
  file?: File,
  options?: { [key: string]: any }
) {
  const formData = new FormData();

  if (file) {
    formData.append("file", file);
  }

  Object.keys(body).forEach((ele) => {
    const item = (body as any)[ele];

    if (item !== undefined && item !== null) {
      if (typeof item === "object" && !(item instanceof File)) {
        if (item instanceof Array) {
          item.forEach((f) => formData.append(ele, f || ""));
        } else {
          formData.append(ele, JSON.stringify(item));
        }
      } else {
        formData.append(ele, item);
      }
    }
  });

  return request<any>("/api/v1/videos/upload", {
    method: "POST",
    data: formData,
    requestType: "form",
    ...(options || {}),
  });
}
