// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all tags GET /tags */
export async function tagControllerFindAll(
  // Param type generated by superposition
  params: API.TagControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<any>("/tags", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create a new tag POST /tags */
export async function tagControllerCreate(
  body: API.CreateTagDto,
  options?: { [key: string]: any }
) {
  return request<any>("/tags", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get a tag by ID GET /tags/${param0} */
export async function tagControllerFindOne(
  // Param type generated by superposition
  params: API.TagControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/tags/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update a tag PUT /tags/${param0} */
export async function tagControllerUpdate(
  // Param type generated by superposition
  params: API.TagControllerUpdateParams,
  body: API.UpdateTagDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/tags/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete a tag DELETE /tags/${param0} */
export async function tagControllerRemove(
  // Param type generated by superposition
  params: API.TagControllerRemoveParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/tags/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}
