// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all tags GET /api/v1/tags */
export async function tagsControllerGetTags(
  // Param type generated by superposition
  params: API.TagsControllerGetTagsParams,
  options?: { [key: string]: any }
) {
  return request<API.TagDtoPaginatedResponseDto>("/api/v1/tags", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create a new tag POST /api/v1/tags */
export async function tagsControllerCreateTag(
  body: API.CreateTagDto,
  options?: { [key: string]: any }
) {
  return request<API.TagDtoResponseDto>("/api/v1/tags", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get tag by ID GET /api/v1/tags/${param0} */
export async function tagsControllerGetTagById(
  // Param type generated by superposition
  params: API.TagsControllerGetTagByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.TagDtoResponseDto>(`/api/v1/tags/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update a tag PUT /api/v1/tags/${param0} */
export async function tagsControllerUpdateTag(
  // Param type generated by superposition
  params: API.TagsControllerUpdateTagParams,
  body: API.UpdateTagDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.TagDtoResponseDto>(`/api/v1/tags/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete a tag DELETE /api/v1/tags/${param0} */
export async function tagsControllerDeleteTag(
  // Param type generated by superposition
  params: API.TagsControllerDeleteTagParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/tags/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Search tags GET /api/v1/tags/search */
export async function tagsControllerSearchTags(
  // Param type generated by superposition
  params: API.TagsControllerSearchTagsParams,
  options?: { [key: string]: any }
) {
  return request<API.TagDtoResponseDto>("/api/v1/tags/search", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}
