// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get TV series list GET /api/v1/tv-series */
export async function tvSeriesControllerGetTvSeries(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetTvSeriesParams,
  options?: { [key: string]: any }
) {
  return request<API.TVSeriesSummaryDtoPaginatedResponseDto>(
    "/api/v1/tv-series",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** [ADMIN] Create TV series POST /api/v1/tv-series */
export async function tvSeriesControllerCreateTvSeries(
  body: API.CreateTVSeriesDto,
  options?: { [key: string]: any }
) {
  return request<API.TVSeriesDto>("/api/v1/tv-series", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get TV series detail by ID GET /api/v1/tv-series/${param0} */
export async function tvSeriesControllerGetTvSeriesById(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetTvSeriesByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.TVSeriesDto>(`/api/v1/tv-series/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update TV series PUT /api/v1/tv-series/${param0} */
export async function tvSeriesControllerUpdateTvSeries(
  // Param type generated by superposition
  params: API.TvSeriesControllerUpdateTvSeriesParams,
  body: API.UpdateTVSeriesDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.TVSeriesDto>(`/api/v1/tv-series/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete TV series DELETE /api/v1/tv-series/${param0} */
export async function tvSeriesControllerDeleteTvSeries(
  // Param type generated by superposition
  params: API.TvSeriesControllerDeleteTvSeriesParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/tv-series/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get related TV series GET /api/v1/tv-series/${param0}/related */
export async function tvSeriesControllerGetRelatedTvSeries(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetRelatedTvSeriesParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.TVSeriesSummaryDtoPaginatedResponseDto>(
    `/api/v1/tv-series/${param0}/related`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}

/** Get TV series by category GET /api/v1/tv-series/category/${param0} */
export async function tvSeriesControllerGetTvSeriesByCategory(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetTvSeriesByCategoryParams,
  options?: { [key: string]: any }
) {
  const { categoryId: param0, ...queryParams } = params;
  return request<API.TVSeriesSummaryDtoPaginatedResponseDto>(
    `/api/v1/tv-series/category/${param0}`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}

/** Get TV series with latest episodes GET /api/v1/tv-series/new-episodes */
export async function tvSeriesControllerGetTvSeriesWithNewEpisodes(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetTvSeriesWithNewEpisodesParams,
  options?: { [key: string]: any }
) {
  return request<API.TVSeriesSummaryDtoPaginatedResponseDto>(
    "/api/v1/tv-series/new-episodes",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get trending TV series GET /api/v1/tv-series/trending */
export async function tvSeriesControllerGetTrendingTvSeries(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetTrendingTvSeriesParams,
  options?: { [key: string]: any }
) {
  return request<API.TVSeriesSummaryDtoPaginatedResponseDto>(
    "/api/v1/tv-series/trending",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}
