// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all movies GET /tvseries */
export async function tvSeriesControllerFindAll(
  // Param type generated by superposition
  params: API.TvSeriesControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.TVSeriesSummaryDtoPaginatedResponseDto>("/tvseries", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Create a new TV series POST /tvseries */
export async function tvSeriesControllerCreate(
  body: API.CreateTVSeriesDto,
  options?: { [key: string]: any }
) {
  return request<API.TVSeriesDtoResponseDto>("/tvseries", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get TV series by ID GET /tvseries/${param0} */
export async function tvSeriesControllerFindOne(
  // Param type generated by superposition
  params: API.TvSeriesControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.TVSeriesDtoResponseDto>(`/tvseries/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update a TV series PUT /tvseries/${param0} */
export async function tvSeriesControllerUpdate(
  // Param type generated by superposition
  params: API.TvSeriesControllerUpdateParams,
  body: API.UpdateTVSeriesDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.TVSeriesDtoResponseDto>(`/tvseries/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete a TV series DELETE /tvseries/${param0} */
export async function tvSeriesControllerRemove(
  // Param type generated by superposition
  params: API.TvSeriesControllerRemoveParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/tvseries/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get TV series by category ID GET /tvseries/category/${param0} */
export async function tvSeriesControllerGetTvSeriesByCategoryId(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetTvSeriesByCategoryIdParams,
  options?: { [key: string]: any }
) {
  const { categoryId: param0, ...queryParams } = params;
  return request<API.TVSeriesSummaryDtoPaginatedResponseDto>(
    `/tvseries/category/${param0}`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}

/** Get TV series with new episodes GET /tvseries/new-episodes */
export async function tvSeriesControllerGetTvSeriesWithNewEpisodes(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetTvSeriesWithNewEpisodesParams,
  options?: { [key: string]: any }
) {
  return request<API.TVSeriesWithNewEpisodePaginatedResponseDto>(
    "/tvseries/new-episodes",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get TV series recommendations by ID GET /tvseries/recommendations/${param0} */
export async function tvSeriesControllerGetRecommendations(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetRecommendationsParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.TVSeriesSummaryDtoPaginatedResponseDto>(
    `/tvseries/recommendations/${param0}`,
    {
      method: "GET",
      params: {
        ...queryParams,
      },
      ...(options || {}),
    }
  );
}

/** Get trending TV series GET /tvseries/trending */
export async function tvSeriesControllerGetTrendingSeries(
  // Param type generated by superposition
  params: API.TvSeriesControllerGetTrendingSeriesParams,
  options?: { [key: string]: any }
) {
  return request<API.TVSeriesSummaryDtoPaginatedResponseDto>(
    "/tvseries/trending",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}
