// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all users (Admin only) GET /users */
export async function userControllerFindAll(
  // Param type generated by superposition
  params: API.UserControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.UserDtoPaginatedResponseDto>("/users", {
    method: "GET",
    params: {
      // search has a default value: 1
      search: "1",

      // limit has a default value: 10
      limit: "10",
      // page has a default value: 1
      page: "1",
      ...params,
    },
    ...(options || {}),
  });
}

/** No comments are provided by the backend POST /users */
export async function userControllerCreate(
  body: API.CreateUserDto,
  options?: { [key: string]: any }
) {
  return request<API.UserDtoResponseDto>("/users", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** No comments are provided by the backend PUT /users/${param0} */
export async function userControllerUpdate(
  // Param type generated by superposition
  params: API.UserControllerUpdateParams,
  body: API.UpdateUserDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.UserDtoResponseDto>(`/users/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** No comments are provided by the backend DELETE /users/${param0} */
export async function userControllerDelete(
  // Param type generated by superposition
  params: API.UserControllerDeleteParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/users/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Ban user (Admin only) POST /users/${param0}/ban */
export async function userControllerBanUser(
  // Param type generated by superposition
  params: API.UserControllerBanUserParams,
  body: API.BanUserDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.UserDetailDtoResponseDto>(`/users/${param0}/ban`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** Get user detail (Admin only) GET /users/${param0}/detail */
export async function userControllerGetUserDetail(
  // Param type generated by superposition
  params: API.UserControllerGetUserDetailParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.UserDetailDtoResponseDto>(`/users/${param0}/detail`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Update user info (Admin only) PUT /users/${param0}/info */
export async function userControllerUpdateUserInfo(
  // Param type generated by superposition
  params: API.UserControllerUpdateUserInfoParams,
  body: API.UpdateUserInfoDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.UserDetailDtoResponseDto>(`/users/${param0}/info`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** Unban user (Admin only) DELETE /users/${param0}/unban */
export async function userControllerUnbanUser(
  // Param type generated by superposition
  params: API.UserControllerUnbanUserParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.UserDetailDtoResponseDto>(`/users/${param0}/unban`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get user profile Get the current user profile information GET /users/profile */
export async function userControllerGetProfile(options?: {
  [key: string]: any;
}) {
  return request<API.ProfileResponse>("/users/profile", {
    method: "GET",
    ...(options || {}),
  });
}

/** Update user profile Update user basic information (name, gender, date of birth, address, phone) PUT /users/profile */
export async function userControllerUpdateProfile(
  body: API.UpdateProfileRequest,
  options?: { [key: string]: any }
) {
  return request<API.ProfileResponse>("/users/profile", {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Update avatar Update avatar with a new URL for the current user PUT /users/profile/avatar */
export async function userControllerUpdateAvatar(
  body: API.UpdateAvatarRequest,
  options?: { [key: string]: any }
) {
  return request<API.UploadAvatarResponse>("/users/profile/avatar", {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Delete avatar Delete the current user avatar DELETE /users/profile/avatar */
export async function userControllerDeleteAvatar(options?: {
  [key: string]: any;
}) {
  return request<{ success?: boolean; message?: string }>(
    "/users/profile/avatar",
    {
      method: "DELETE",
      ...(options || {}),
    }
  );
}

/** Change password Change the current user password POST /users/profile/change-password */
export async function userControllerChangePassword(
  body: API.ChangePasswordRequest,
  options?: { [key: string]: any }
) {
  return request<API.ProfileResponse>("/users/profile/change-password", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}
