// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get videos list GET /api/v1/videos */
export async function videosControllerGetVideos(
  // Param type generated by superposition
  params: API.VideosControllerGetVideosParams,
  options?: { [key: string]: any }
) {
  return request<API.VideoDtoPaginatedResponseDto>("/api/v1/videos", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create video POST /api/v1/videos */
export async function videosControllerCreateVideo(
  body: API.CreateVideoDto,
  options?: { [key: string]: any }
) {
  return request<API.VideoDto>("/api/v1/videos", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get video detail by ID GET /api/v1/videos/${param0} */
export async function videosControllerGetVideoById(
  // Param type generated by superposition
  params: API.VideosControllerGetVideoByIdParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.VideoDto>(`/api/v1/videos/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update video PUT /api/v1/videos/${param0} */
export async function videosControllerUpdateVideo(
  // Param type generated by superposition
  params: API.VideosControllerUpdateVideoParams,
  body: API.UpdateVideoDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.VideoDto>(`/api/v1/videos/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete video DELETE /api/v1/videos/${param0} */
export async function videosControllerDeleteVideo(
  // Param type generated by superposition
  params: API.VideosControllerDeleteVideoParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/videos/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}
