// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all videos GET /videos */
export async function videoControllerFindAll(
  // Param type generated by superposition
  params: API.VideoControllerFindAllParams,
  options?: { [key: string]: any }
) {
  return request<API.VideoDtoPaginatedResponseDto>("/videos", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** [ADMIN] Create new video POST /videos */
export async function videoControllerCreate(
  body: API.CreateVideoDto,
  options?: { [key: string]: any }
) {
  return request<API.VideoDtoResponseDto>("/videos", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get video by ID GET /videos/${param0} */
export async function videoControllerFindOne(
  // Param type generated by superposition
  params: API.VideoControllerFindOneParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.VideoDtoResponseDto>(`/videos/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Update video PUT /videos/${param0} */
export async function videoControllerUpdate(
  // Param type generated by superposition
  params: API.VideoControllerUpdateParams,
  body: API.UpdateVideoDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<API.VideoDtoResponseDto>(`/videos/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** [ADMIN] Delete video DELETE /videos/${param0} */
export async function videoControllerDelete(
  // Param type generated by superposition
  params: API.VideoControllerDeleteParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/videos/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** No comments are provided by the backend GET /videos/${param0}/access */
export async function videoControllerGetFileAccess(
  // Param type generated by superposition
  params: API.VideoControllerGetFileAccessParams,
  options?: { [key: string]: any }
) {
  const { s3Key: param0, ...queryParams } = params;
  return request<any>(`/videos/${param0}/access`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** [ADMIN] Upload video for HLS encoding POST /videos/upload */
export async function videoControllerUploadVideo(
  body: {},
  file?: File,
  options?: { [key: string]: any }
) {
  const formData = new FormData();

  if (file) {
    formData.append("file", file);
  }

  Object.keys(body).forEach((ele) => {
    const item = (body as any)[ele];

    if (item !== undefined && item !== null) {
      if (typeof item === "object" && !(item instanceof File)) {
        if (item instanceof Array) {
          item.forEach((f) => formData.append(ele, f || ""));
        } else {
          formData.append(ele, JSON.stringify(item));
        }
      } else {
        formData.append(ele, item);
      }
    }
  });

  return request<any>("/videos/upload", {
    method: "POST",
    data: formData,
    requestType: "form",
    ...(options || {}),
  });
}
