// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** List all watch-party rooms (admin) GET /api/v1/watch-party/admin/rooms */
export async function watchPartyControllerAdminListRooms(
  // Param type generated by superposition
  params: API.WatchPartyControllerAdminListRoomsParams,
  options?: { [key: string]: any }
) {
  return request<API.RoomListResponseResponseDto>(
    "/api/v1/watch-party/admin/rooms",
    {
      method: "GET",
      params: {
        // limit has a default value: 20
        limit: "20",

        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get watch-party room details (admin) GET /api/v1/watch-party/admin/rooms/${param0} */
export async function watchPartyControllerAdminGetRoomDetails(
  // Param type generated by superposition
  params: API.WatchPartyControllerAdminGetRoomDetailsParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watch-party/admin/rooms/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Force-close a watch-party room (admin) DELETE /api/v1/watch-party/admin/rooms/${param0} */
export async function watchPartyControllerAdminCloseRoom(
  // Param type generated by superposition
  params: API.WatchPartyControllerAdminCloseRoomParams,
  body: API.AdminCloseRoomDto,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watch-party/admin/rooms/${param0}`, {
    method: "DELETE",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** Kick a member from a watch-party room (admin) DELETE /api/v1/watch-party/admin/rooms/${param0}/members/${param1} */
export async function watchPartyControllerAdminKickMember(
  // Param type generated by superposition
  params: API.WatchPartyControllerAdminKickMemberParams,
  options?: { [key: string]: any }
) {
  const { id: param0, userId: param1, ...queryParams } = params;
  return request<any>(
    `/api/v1/watch-party/admin/rooms/${param0}/members/${param1}`,
    {
      method: "DELETE",
      params: { ...queryParams },
      ...(options || {}),
    }
  );
}

/** Get watch-party system statistics (admin) GET /api/v1/watch-party/admin/stats */
export async function watchPartyControllerAdminGetStats(options?: {
  [key: string]: any;
}) {
  return request<API.WatchPartyStatsResponseResponseDto>(
    "/api/v1/watch-party/admin/stats",
    {
      method: "GET",
      ...(options || {}),
    }
  );
}

/** Global-ban a user from Watch Party (admin) POST /api/v1/watch-party/admin/users/${param0}/ban */
export async function watchPartyControllerAdminBanUser(
  // Param type generated by superposition
  params: API.WatchPartyControllerAdminBanUserParams,
  body: API.AdminBanUserDto,
  options?: { [key: string]: any }
) {
  const { userId: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watch-party/admin/users/${param0}/ban`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** Remove global Watch Party ban from a user (admin) DELETE /api/v1/watch-party/admin/users/${param0}/ban */
export async function watchPartyControllerAdminUnbanUser(
  // Param type generated by superposition
  params: API.WatchPartyControllerAdminUnbanUserParams,
  options?: { [key: string]: any }
) {
  const { userId: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watch-party/admin/users/${param0}/ban`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get the active room for the current user GET /api/v1/watch-party/my-rooms */
export async function watchPartyControllerMyRoom(options?: {
  [key: string]: any;
}) {
  return request<any>("/api/v1/watch-party/my-rooms", {
    method: "GET",
    ...(options || {}),
  });
}

/** List active watch-party rooms (newest first) GET /api/v1/watch-party/rooms */
export async function watchPartyControllerListRooms(
  // Param type generated by superposition
  params: API.WatchPartyControllerListRoomsParams,
  options?: { [key: string]: any }
) {
  return request<API.RoomListResponseResponseDto>("/api/v1/watch-party/rooms", {
    method: "GET",
    params: {
      // scope has a default value: public
      scope: "public",
      // limit has a default value: 20
      limit: "20",

      ...params,
    },
    ...(options || {}),
  });
}

/** Create a new watch-party room POST /api/v1/watch-party/rooms */
export async function watchPartyControllerCreateRoom(
  body: API.CreateRoomRequest,
  options?: { [key: string]: any }
) {
  return request<API.CreateRoomResponseResponseDto>(
    "/api/v1/watch-party/rooms",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      data: body,
      ...(options || {}),
    }
  );
}

/** Host closes the room DELETE /api/v1/watch-party/rooms/${param0} */
export async function watchPartyControllerCloseRoom(
  // Param type generated by superposition
  params: API.WatchPartyControllerCloseRoomParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watch-party/rooms/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Look up a room by invite code GET /api/v1/watch-party/rooms/invite/${param0} */
export async function watchPartyControllerLookupInvite(
  // Param type generated by superposition
  params: API.WatchPartyControllerLookupInviteParams,
  options?: { [key: string]: any }
) {
  const { code: param0, ...queryParams } = params;
  return request<API.InviteLookupResponseResponseDto>(
    `/api/v1/watch-party/rooms/invite/${param0}`,
    {
      method: "GET",
      params: { ...queryParams },
      ...(options || {}),
    }
  );
}
