// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get the active room for the current user GET /api/v1/watch-party/my-rooms */
export async function watchPartyControllerMyRoom(options?: {
  [key: string]: any;
}) {
  return request<any>("/api/v1/watch-party/my-rooms", {
    method: "GET",
    ...(options || {}),
  });
}

/** List active watch-party rooms (newest first) GET /api/v1/watch-party/rooms */
export async function watchPartyControllerListRooms(
  // Param type generated by superposition
  params: API.WatchPartyControllerListRoomsParams,
  options?: { [key: string]: any }
) {
  return request<API.RoomListResponseResponseDto>("/api/v1/watch-party/rooms", {
    method: "GET",
    params: {
      // scope has a default value: public
      scope: "public",
      // limit has a default value: 20
      limit: "20",

      ...params,
    },
    ...(options || {}),
  });
}

/** Create a new watch-party room POST /api/v1/watch-party/rooms */
export async function watchPartyControllerCreateRoom(
  body: API.CreateRoomRequest,
  options?: { [key: string]: any }
) {
  return request<API.CreateRoomResponseResponseDto>(
    "/api/v1/watch-party/rooms",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      data: body,
      ...(options || {}),
    }
  );
}

/** Host closes the room DELETE /api/v1/watch-party/rooms/${param0} */
export async function watchPartyControllerCloseRoom(
  // Param type generated by superposition
  params: API.WatchPartyControllerCloseRoomParams,
  options?: { [key: string]: any }
) {
  const { id: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watch-party/rooms/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Force-close a watch-party room (admin) DELETE /api/v1/watch-party/admin/rooms/${param0} */
export async function watchPartyAdminCloseRoom(
  params: { id: string; reason?: string },
  options?: { [key: string]: any }
) {
  const { id: param0, ...body } = params;
  return request<any>(`/api/v1/watch-party/admin/rooms/${param0}`, {
    method: "DELETE",
    headers: { "Content-Type": "application/json" },
    data: body,
    ...(options || {}),
  });
}

/** Look up a room by invite code GET /api/v1/watch-party/rooms/invite/${param0} */
export async function watchPartyControllerLookupInvite(
  // Param type generated by superposition
  params: API.WatchPartyControllerLookupInviteParams,
  options?: { [key: string]: any }
) {
  const { code: param0, ...queryParams } = params;
  return request<API.InviteLookupResponseResponseDto>(
    `/api/v1/watch-party/rooms/invite/${param0}`,
    {
      method: "GET",
      params: { ...queryParams },
      ...(options || {}),
    }
  );
}
