// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get user watchlist GET /api/v1/watchlist */
export async function watchListControllerGetUserWatchList(
  // Param type generated by superposition
  params: API.WatchListControllerGetUserWatchListParams,
  options?: { [key: string]: any }
) {
  return request<any>("/api/v1/watchlist", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Add content to watchlist POST /api/v1/watchlist */
export async function watchListControllerAddToWatchList(
  body: API.CreateWatchListDto,
  options?: { [key: string]: any }
) {
  return request<any>("/api/v1/watchlist", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Remove content from watchlist DELETE /api/v1/watchlist/${param0} */
export async function watchListControllerRemoveFromWatchList(
  // Param type generated by superposition
  params: API.WatchListControllerRemoveFromWatchListParams,
  options?: { [key: string]: any }
) {
  const { contentId: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watchlist/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Check if movie/tvseries is in watchlist by movie/tvseries ID GET /api/v1/watchlist/check-movie/${param0} */
export async function watchListControllerCheckInWatchListByMovieId(
  // Param type generated by superposition
  params: API.WatchListControllerCheckInWatchListByMovieIdParams,
  options?: { [key: string]: any }
) {
  const { movieId: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watchlist/check-movie/${param0}`, {
    method: "GET",
    params: {
      ...queryParams,
    },
    ...(options || {}),
  });
}

/** Check if content is in watchlist by content ID GET /api/v1/watchlist/check/${param0} */
export async function watchListControllerCheckInWatchList(
  // Param type generated by superposition
  params: API.WatchListControllerCheckInWatchListParams,
  options?: { [key: string]: any }
) {
  const { contentId: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watchlist/check/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Get count of users who added content to favourites GET /api/v1/watchlist/favourite-count/${param0} */
export async function watchListControllerGetFavouriteCount(
  // Param type generated by superposition
  params: API.WatchListControllerGetFavouriteCountParams,
  options?: { [key: string]: any }
) {
  const { contentId: param0, ...queryParams } = params;
  return request<any>(`/api/v1/watchlist/favourite-count/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}
