// @ts-ignore
/* eslint-disable */
import request from "@/lib/request";

/** Get all watch progress for current user GET /watch-progress */
export async function watchProgressControllerGetAllWatchProgress(
  // Param type generated by superposition
  params: API.WatchProgressControllerGetAllWatchProgressParams,
  options?: { [key: string]: any }
) {
  return request<API.WatchProgressDtoPaginatedResponseDto>("/watch-progress", {
    method: "GET",
    params: {
      ...params,
    },
    ...(options || {}),
  });
}

/** Create or update watch progress for a content POST /watch-progress */
export async function watchProgressControllerCreateOrUpdateWatchProgress(
  body: API.CreateWatchProgressDto,
  options?: { [key: string]: any }
) {
  return request<API.WatchProgressDtoResponseDto>("/watch-progress", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    data: body,
    ...(options || {}),
  });
}

/** Get watch progress for a specific video GET /watch-progress/${param0} */
export async function watchProgressControllerGetWatchProgress(
  // Param type generated by superposition
  params: API.WatchProgressControllerGetWatchProgressParams,
  options?: { [key: string]: any }
) {
  const { videoId: param0, ...queryParams } = params;
  return request<API.WatchProgressDto>(`/watch-progress/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Update watch progress for a specific video PUT /watch-progress/${param0} */
export async function watchProgressControllerUpdateProgress(
  // Param type generated by superposition
  params: API.WatchProgressControllerUpdateProgressParams,
  body: API.UpdateWatchProgressDto,
  options?: { [key: string]: any }
) {
  const { videoId: param0, ...queryParams } = params;
  return request<API.WatchProgressDtoResponseDto>(`/watch-progress/${param0}`, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
    },
    params: { ...queryParams },
    data: body,
    ...(options || {}),
  });
}

/** Delete watch progress for a video DELETE /watch-progress/${param0} */
export async function watchProgressControllerDeleteWatchProgress(
  // Param type generated by superposition
  params: API.WatchProgressControllerDeleteWatchProgressParams,
  options?: { [key: string]: any }
) {
  const { videoId: param0, ...queryParams } = params;
  return request<any>(`/watch-progress/${param0}`, {
    method: "DELETE",
    params: { ...queryParams },
    ...(options || {}),
  });
}

/** Mark video as completed PUT /watch-progress/${param0}/complete */
export async function watchProgressControllerMarkAsCompleted(
  // Param type generated by superposition
  params: API.WatchProgressControllerMarkAsCompletedParams,
  options?: { [key: string]: any }
) {
  const { videoId: param0, ...queryParams } = params;
  return request<API.WatchProgressDtoResponseDto>(
    `/watch-progress/${param0}/complete`,
    {
      method: "PUT",
      params: { ...queryParams },
      ...(options || {}),
    }
  );
}

/** Get watch history GET /watch-progress/history */
export async function watchProgressControllerGetWatchHistory(
  // Param type generated by superposition
  params: API.WatchProgressControllerGetWatchHistoryParams,
  options?: { [key: string]: any }
) {
  return request<API.WatchProgressDtoPaginatedResponseDto>(
    "/watch-progress/history",
    {
      method: "GET",
      params: {
        ...params,
      },
      ...(options || {}),
    }
  );
}

/** Get recently watched contents for quick resume GET /watch-progress/recently-watched */
export async function watchProgressControllerGetRecentlyWatched(options?: {
  [key: string]: any;
}) {
  return request<API.WatchProgressDto[]>("/watch-progress/recently-watched", {
    method: "GET",
    ...(options || {}),
  });
}

/** Get resume data to continue watching GET /watch-progress/resume/${param0} */
export async function watchProgressControllerGetResumeData(
  // Param type generated by superposition
  params: API.WatchProgressControllerGetResumeDataParams,
  options?: { [key: string]: any }
) {
  const { videoId: param0, ...queryParams } = params;
  return request<any>(`/watch-progress/resume/${param0}`, {
    method: "GET",
    params: { ...queryParams },
    ...(options || {}),
  });
}
